on:
  push:
    # This action runs on PRs, so no need to rerun it on master/main
    branches-ignore:
      - master
      - main
    paths:
    - '**.tf'
    - '**.tfvars'
    - '**.tfvars.json'
jobs:
  infracost:
    runs-on: ubuntu-latest
    name: Show infracost diff
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: "Install terraform"
      uses: hashicorp/setup-terraform@v1

    - name: "Terraform init"
      id: init
      run: terraform init
      working-directory: terraform

    - name: "Terraform plan"
      id: plan
      run: terraform plan -out plan.tfplan
      working-directory: terraform

    - name: "Terraform show"
      id: show
      run: terraform show -json plan.tfplan
      working-directory: terraform
      
    - name: "Save Plan JSON"
      run: echo '${{ steps.show.outputs.stdout }}' > plan.json

    - name: Run infracost diff
      uses: infracost/infracost-gh-action@master
      env:
        INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        entrypoint: /scripts/ci/diff.sh # Do not change
        path: plan.json
        usage_file: infracost-usage.yml
